// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "RiffNode",
    platforms: [
        .macOS("26.0"),
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "RiffNode",
            targets: ["AppModule"],
            bundleIdentifier: "com.yujia.RiffNode",
            teamIdentifier: "GJRVCWA2U3",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .mac
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown,
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .microphone(purposeString: "RiffNode needs microphone access to process your guitar input through the effects chain."),
                .camera(purposeString: "RiffNode uses the camera for hands-free gesture control - control effects with head movements while playing."),
                .fileAccess(.userSelectedFiles, mode: .readOnly),
                .fileAccess(.downloadsFolder, mode: .readOnly),
                .fileAccess(.musicFolder, mode: .readOnly),
                .fileAccess(.pictureFolder, mode: .readOnly),
                .fileAccess(.moviesFolder, mode: .readOnly)
            ],
            appCategory: .music
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageModes: [.v6]
)