import Foundation
import Observation

#if canImport(FoundationModels)
import FoundationModels
#endif

// MARK: - Generable Output Types

/// Tone parameters generated by Foundation Models
/// Using @Generable for structured output from on-device LLM
#if canImport(FoundationModels)
@available(iOS 26, macOS 26, *)
@Generable
struct ToneParameters: Sendable {
    @Guide(description: "Reverb wetDryMix from 0 to 100, higher = more spacious")
    var reverbMix: Double

    @Guide(description: "Delay mix from 0 to 100, higher = more echoes")
    var delayMix: Double

    @Guide(description: "Delay time in seconds from 0.0 to 2.0")
    var delayTime: Double

    @Guide(description: "Distortion drive from 0 to 100, higher = more aggressive")
    var distortionDrive: Double

    @Guide(description: "Chorus depth from 0 to 100, higher = more modulation")
    var chorusDepth: Double

    @Guide(description: "EQ bass adjustment from -12 to 12 dB")
    var eqBass: Double

    @Guide(description: "EQ mid adjustment from -12 to 12 dB")
    var eqMid: Double

    @Guide(description: "EQ treble adjustment from -12 to 12 dB")
    var eqTreble: Double

    @Guide(description: "Brief explanation of the tone settings")
    var explanation: String
}

@available(iOS 26, macOS 26, *)
@Generable
struct EffectRecommendation: Sendable {
    @Guide(description: "List of effect types to enable: compressor, overdrive, distortion, fuzz, chorus, phaser, flanger, tremolo, delay, reverb, equalizer")
    var enabledEffects: [String]

    @Guide(description: "The tone parameters to apply")
    var parameters: ToneParameters
}
#endif

// MARK: - Fallback Types (for older OS versions)

/// Fallback tone parameters when Foundation Models unavailable
struct FallbackToneParameters: Sendable {
    var reverbMix: Double = 40
    var delayMix: Double = 30
    var delayTime: Double = 0.3
    var distortionDrive: Double = 50
    var chorusDepth: Double = 40
    var eqBass: Double = 0
    var eqMid: Double = 0
    var eqTreble: Double = 0
    var explanation: String = "Default tone settings"
}

/// Fallback effect recommendation when Foundation Models unavailable
struct FallbackEffectRecommendation: Sendable {
    var enabledEffects: [String] = ["distortion", "reverb"]
    var parameters: FallbackToneParameters = FallbackToneParameters()
}

// MARK: - Semantic Command Processor

/// Processes natural language commands into DSP parameters using Foundation Models
/// Gracefully degrades to preset-based suggestions on older devices
@Observable
@MainActor
final class SemanticCommandProcessor {

    // MARK: - State

    private(set) var isProcessing = false
    private(set) var lastCommand: String = ""
    private(set) var lastEnabledEffects: [String] = []
    private(set) var lastParameters: FallbackToneParameters?
    private(set) var lastExplanation: String = ""
    private(set) var errorMessage: String?
    private(set) var isAvailable = false

    // MARK: - Foundation Models Session

    #if canImport(FoundationModels)
    @available(iOS 26, macOS 26, *)
    private var session: LanguageModelSession?
    #endif

    // MARK: - Initialization

    init() {
        Task {
            await checkAvailability()
        }
    }

    // MARK: - Availability Check

    private func checkAvailability() async {
        #if canImport(FoundationModels)
        if #available(iOS 26, macOS 26, *) {
            let session = LanguageModelSession()
            self.session = session
            isAvailable = true
        } else {
            isAvailable = false
            errorMessage = "AI features require iOS 26+"
        }
        #else
        isAvailable = false
        errorMessage = "Foundation Models not available on this platform"
        #endif
    }

    // MARK: - Process Command

    /// Process a natural language command and return effect recommendations
    func processCommand(_ command: String) async -> Bool {
        isProcessing = true
        lastCommand = command
        errorMessage = nil

        defer { isProcessing = false }

        #if canImport(FoundationModels)
        if #available(iOS 26, macOS 26, *), isAvailable, let session = session {
            let systemPrompt = """
            You are a guitar tone expert. Given a natural language description of a desired guitar sound,
            recommend which effects to enable and their parameter values.

            Available effects: compressor, overdrive, distortion, fuzz, chorus, phaser, flanger, tremolo, delay, reverb, equalizer

            Parameter ranges:
            - reverbMix, delayMix, distortionDrive, chorusDepth: 0-100
            - delayTime: 0.0-2.0 seconds
            - eqBass, eqMid, eqTreble: -12 to 12 dB

            Common tone mappings:
            - "spacey/ambient" -> high reverb (60-80), delay (40-60), chorus (30-50)
            - "heavy/metal" -> distortion (70-100), bass boost, mid scoop
            - "clean/crystal" -> low distortion, slight reverb (20-30), treble boost
            - "warm/vintage" -> overdrive (30-50), bass boost, reverb (30-40)
            - "80s" -> chorus (50-70), delay (40), reverb (40)
            """

            do {
                let response = try await session.respond(
                    to: "\(systemPrompt)\n\nUser request: \(command)",
                    generating: EffectRecommendation.self
                )

                // Access the generated content from the response
                let result = response.content

                // Store results
                lastEnabledEffects = result.enabledEffects
                lastParameters = FallbackToneParameters(
                    reverbMix: result.parameters.reverbMix,
                    delayMix: result.parameters.delayMix,
                    delayTime: result.parameters.delayTime,
                    distortionDrive: result.parameters.distortionDrive,
                    chorusDepth: result.parameters.chorusDepth,
                    eqBass: result.parameters.eqBass,
                    eqMid: result.parameters.eqMid,
                    eqTreble: result.parameters.eqTreble,
                    explanation: result.parameters.explanation
                )
                lastExplanation = result.parameters.explanation
                return true
            } catch {
                errorMessage = "Failed to process: \(error.localizedDescription)"
                return false
            }
        }
        #endif

        // Fallback: Use keyword matching for basic recommendations
        return processCommandFallback(command)
    }

    // MARK: - Fallback Processing

    private func processCommandFallback(_ command: String) -> Bool {
        let lowercased = command.lowercased()

        var effects: [String] = []
        var params = FallbackToneParameters()

        // Keyword-based tone matching
        if lowercased.contains("spacey") || lowercased.contains("ambient") || lowercased.contains("atmospheric") {
            effects = ["reverb", "delay", "chorus"]
            params.reverbMix = 70
            params.delayMix = 50
            params.delayTime = 0.4
            params.chorusDepth = 40
            params.explanation = "Spacey ambient tone with lush reverb, delay, and subtle chorus modulation."
        } else if lowercased.contains("heavy") || lowercased.contains("metal") || lowercased.contains("aggressive") {
            effects = ["distortion", "equalizer"]
            params.distortionDrive = 85
            params.eqBass = 4
            params.eqMid = -3
            params.eqTreble = 2
            params.explanation = "Heavy metal tone with high-gain distortion and scooped mids."
        } else if lowercased.contains("clean") || lowercased.contains("crystal") || lowercased.contains("bright") {
            effects = ["reverb", "equalizer"]
            params.reverbMix = 25
            params.distortionDrive = 0
            params.eqTreble = 4
            params.explanation = "Crystal clean tone with subtle reverb and bright highs."
        } else if lowercased.contains("warm") || lowercased.contains("vintage") || lowercased.contains("blues") {
            effects = ["overdrive", "reverb"]
            params.distortionDrive = 40
            params.reverbMix = 35
            params.eqBass = 3
            params.eqMid = 2
            params.explanation = "Warm vintage blues tone with smooth overdrive and natural reverb."
        } else if lowercased.contains("80s") || lowercased.contains("eighties") || lowercased.contains("synth") {
            effects = ["chorus", "delay", "reverb"]
            params.chorusDepth = 60
            params.delayMix = 45
            params.delayTime = 0.35
            params.reverbMix = 40
            params.explanation = "Classic 80s sound with thick chorus, rhythmic delay, and spacious reverb."
        } else if lowercased.contains("crunch") || lowercased.contains("rock") {
            effects = ["overdrive", "reverb"]
            params.distortionDrive = 55
            params.reverbMix = 30
            params.explanation = "Classic rock crunch with medium overdrive and room reverb."
        } else if lowercased.contains("fuzz") || lowercased.contains("psychedelic") {
            effects = ["fuzz", "reverb", "phaser"]
            params.distortionDrive = 75
            params.reverbMix = 50
            params.explanation = "Psychedelic fuzz tone with swirling phaser and deep reverb."
        } else {
            // Default: balanced tone
            effects = ["distortion", "reverb"]
            params.distortionDrive = 50
            params.reverbMix = 40
            params.explanation = "Balanced tone with moderate distortion and reverb."
        }

        lastEnabledEffects = effects
        lastParameters = params
        lastExplanation = params.explanation
        return true
    }

    // MARK: - Apply to Engine

    /// Apply the last recommendation to the audio engine
    func applyToEngine(_ engine: AudioEngineManager) {
        guard let params = lastParameters else { return }

        // Update effect parameters
        for effect in engine.effectsChain {
            switch effect.type {
            case .reverb:
                let enabled = lastEnabledEffects.contains("reverb")
                effect.isEnabled = enabled
                if enabled {
                    engine.updateEffectParameter(effect, key: "wetDryMix", value: Float(params.reverbMix))
                }

            case .delay:
                let enabled = lastEnabledEffects.contains("delay")
                effect.isEnabled = enabled
                if enabled {
                    engine.updateEffectParameter(effect, key: "mix", value: Float(params.delayMix))
                    engine.updateEffectParameter(effect, key: "time", value: Float(params.delayTime))
                }

            case .distortion:
                let enabled = lastEnabledEffects.contains("distortion")
                effect.isEnabled = enabled
                if enabled {
                    engine.updateEffectParameter(effect, key: "level", value: Float(params.distortionDrive))
                }

            case .chorus:
                let enabled = lastEnabledEffects.contains("chorus")
                effect.isEnabled = enabled

            case .equalizer:
                let enabled = lastEnabledEffects.contains("equalizer")
                effect.isEnabled = enabled
                if enabled {
                    engine.updateEffectParameter(effect, key: "bass", value: Float(params.eqBass))
                    engine.updateEffectParameter(effect, key: "mid", value: Float(params.eqMid))
                    engine.updateEffectParameter(effect, key: "treble", value: Float(params.eqTreble))
                }

            case .overdrive:
                let enabled = lastEnabledEffects.contains("overdrive")
                effect.isEnabled = enabled
                if enabled {
                    engine.updateEffectParameter(effect, key: "level", value: Float(params.distortionDrive))
                }

            case .fuzz:
                effect.isEnabled = lastEnabledEffects.contains("fuzz")

            case .phaser:
                effect.isEnabled = lastEnabledEffects.contains("phaser")

            case .flanger:
                effect.isEnabled = lastEnabledEffects.contains("flanger")

            case .tremolo:
                effect.isEnabled = lastEnabledEffects.contains("tremolo")

            case .compressor:
                effect.isEnabled = lastEnabledEffects.contains("compressor")
            }
        }

        // Rebuild audio chain with new settings
        engine.rebuildEffectsChain()
    }
}
